version: '3.7'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn djangoproj.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mysql:8.0.23
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD:${SQL_PASSWORD}
      - MYSQL_DATABASE:${DB_NAME}
      - MYSQL_USER:${SQL_USER}
      - MYSQL_PASSWORD:${SQL_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql/data/
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    restart: "on-failure"

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume:
  media_volume:
